### ISSUE TITLE
druid-query-timeout argument can cause misunderstanding

### ISSUE THREAD

**Issue by dkhwangbo** [yahoo/sherlock#10]
recently added argument `--druid-query-timeout` is not for druid query timeout. It's just timeout value of HttpClient. 
Description of Druid query timeout is in [this doc](http://druid.io/docs/latest/querying/query-context.html). please check it and change argument name or add real druid query timeout setting.

**Comment by jigs1993** [comment]
@dkhwangbo i will just change the name to `http-client-timeout`
