### ISSUE TITLE
unable to build jar

### ISSUE THREAD

**Issue by p9anand** [yahoo/sherlock#23]
Hi,

Thanks for this amazing library. I was trying to build this. got following error. Please help me to resolve this. Also after build. what command should run to get the UI as you showed in the Demo.

Error: Could not resolve dependencies for project com.yahoo.sherlock:sherlock:jar:1.7-SNAPSHOT: Could not find artifact com.sun:tools:jar:0 at specified path /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home/../lib/tools.jar

**Comment by rpotnuru** [comment]
Looks like you are trying to start using a different jar file: use the generated bulk jar : Here is the command for your reference: 
java -Dlog4j.configuration=file:<<PAHT to Folder>>/sherlock/src/main/resources/log4j.properties \
      -jar sherlock-1.7-SNAPSHOT-jar-with-dependencies.jar \
      --version 1.7 \
      --project-name "Enterprise Frameworks Metrics and Monitoring" \
      --port 8443 \
      --enable-email \
      --failure-email "youramil@yourdomain.com" \
      --from-mail "youramil@yourdomain.com" \
      --reply-to "youramil@yourdomain.com" \
      --smtp-host "smtp.domain.com" \
      --redis-host "<<Redis Host>>" \
      --redis-port <<redis port>> \
      --egads-config-filename <<path to egads config>>/egads_config.ini

And then you can use http://localhost:8443 or http://localhost:8443/sherlock to access the UI.

Hope this helps.

**Comment by guptaraul89** [comment]
I am getting the same error as well when I run `make jar`

`[ERROR] Failed to execute goal on project sherlock: Could not resolve dependencies for project com.yahoo.sherlock:sherlock:jar:1.7-SNAPSHOT: Could not find artifact com.sun:tools:jar:0 at specified path /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home/../lib/tools.jar -> [Help 1]`

**Comment by rpotnuru** [comment]
hi @guptaraul89 , 
You're on JDK >=9  and the JEP 220 removed both tools.jar and rt.jar from the lib folder. Hence you are facing this issue. You can do one of the following to get the app up and running:
Downgrade  to java 8 or  upgrade maven-checkstyle-plugin in the pom file. 
If you are not too much worried bout checkstyle, then you can build the  app by using the below commands
**mvn clean package** 
or 
**mvn -Dmaven.test.skip=true clean package**

**Comment by guptaraul89** [comment]
No luck.
 Currently running java - 
`~/sherlock/sherlock$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)`

and still getting the same error.
`[ERROR] Failed to execute goal on project sherlock: Could not resolve dependencies for project com.yahoo.sherlock:sherlock:jar:1.7-SNAPSHOT: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/java-8-openjdk-amd64/jre/../lib/tools.jar -> [Help 1]`

**Comment by vvagias** [comment]
I have the same issue... Any solution ? 
[ERROR] Failed to execute goal on project sherlock: Could not resolve dependencies for project com.yahoo.sherlock:sherlock:jar:1.11-SNAPSHOT: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.265.b01-0.54.amzn1.x86_64/jre/../lib/tools.jar -> [Help 1]
[ERROR]

**Comment by jigs1993** [comment]
@vvagias i removed cobertura(old plugin) which had system dependency on `com.sun:tools:jar`, can you try now?
