### ISSUE TITLE
FlashQuery is not returning any results

### ISSUE THREAD

**Issue by rpotnuru** [yahoo/sherlock#29]
Hello, I am trying to experiment with this utility to see if it helps some of our use cases and having trouble running a Timeseries query, i am able to run the Timeseries  query against  my druid instance using post man, however  when i run the same query  in flash query UI, i get zero results back. Any help is appreciated in this regard.
Attached is the JSON req and resp used in postman.
[SharlockQuestion.txt](https://github.com/yahoo/sherlock/files/4331175/SharlockQuestion.txt)
Parameters on Falsh Query Screen:
![Sherlock_localhost](https://user-images.githubusercontent.com/3529965/76651686-3e7e9d00-6522-11ea-9077-1844d1c2c4a4.png)

I am using Druid version 0.17.0

**Comment by rpotnuru** [comment]
@jigs1993 , can you please help me with this, this will give me a good start.Appreciate your help.

**Comment by jigs1993** [comment]
Hi @rpotnuru , it looks like you have insufficient data in your druid to run this. It needs atleast 28 days(default: https://github.com/yahoo/sherlock#interval-days) of data to train or same is true for different granularity of data. You can modify this defaults as per your need

**Comment by rpotnuru** [comment]
thank you @jigs1993 , that helped.
