### ISSUE TITLE
Unknown option: --smtp-password

### ISSUE THREAD

**Issue by guptaraul89** [yahoo/sherlock#32]
I downloaded the jar file from [here](https://bintray.com/yahoo/maven/Sherlock/) - 

When I pass stmp password int he cli I get the following error
`Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --smtp-password`

Here is what my command look like.

`java -Dlog4j.configuration=file:/home/ubuntu/sherlock/sherlock/src/main/resources/log4j.properties -jar sherlock-1.5 --version 1.5 --project-name "Metrics and Monitoring" --port 3000 --enable-email --failure-email "myemail@portal.com" --from-mail "general@portal.com" --reply-to "myemail@portal.com" --smtp-host "smtp.outlook.office365.com" --smtp-port 587 --smtp-password "passowrd" --redis-host "127.0.0.1" --redis-port 6379 --egads-config-filename /home/ubuntu/sherlock/sherlock/src/main/resources/egads_config.ini`

**Comment by jigs1993** [comment]
@guptaraul89 please use the latest version of this project
