### ISSUE TITLE
Failed to collect dependencies at com.yahoo.egads:egads:jar:0.4.0

### ISSUE THREAD

**Issue by taylangezici** [yahoo/sherlock#41]
Tried to run the make file. Got an error like this:

> C:\...\sherlock>make jar
> mvn clean checkstyle:check package
> [INFO] Scanning for projects...
> [INFO]
> [INFO] --------------------< com.yahoo.sherlock:sherlock >---------------------
> [INFO] Building sherlock 1.12-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> Downloading from bintray-yahoo-maven: https://yahoo.bintray.com/maven/com/yahoo/egads/egads/0.4.0/egads-0.4.0.pom
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.057 s
> [INFO] Finished at: 2021-09-20T10:34:08+03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project sherlock: Could not resolve dependencies for project com.yahoo.sherlock:sherlock:jar:1.12-SNAPSHOT: Failed to collect dependencies at com.yahoo.egads:egads:jar:0.4.0: Failed to read artifact descriptor for com.yahoo.egads:egads:jar:0.4.0: Could not transfer artifact com.yahoo.egads:egads:pom:0.4.0 from/to bintray-yahoo-maven (https://yahoo.bintray.com/maven): authorization failed for https://yahoo.bintray.com/maven/com/yahoo/egads/egads/0.4.0/egads-0.4.0.pom, status: 403 Forbidden -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> make: *** [Makefile:7: jar] Error 1

any idea how to solve this?

my Apache Maven version is 3.8.2 (latest)

**Comment by jigs1993** [comment]
Hi @taylangezici 

all the artifacts are moved to oss sonatype nexus repo for Yahoo opensource projects. I need to resolve this issue by contacting the owner of this egads artifact and get it available in oss sonatype nexus. I will keep you posted on the progress

**Comment by jigs1993** [comment]
@taylangezici I updated the EGADS version to 4.4.4 which is available [here](https://search.maven.org/artifact/com.yahoo.egads/egads/0.4.4/jar)

you should be able to run your build now
